export const commentTypes = {
    COMMENT_LOAD: "COMMENT_LOAD",
    COMMENT_SUCCESS_ADD: "COMMENT_SUCCESS_ADD",
    COMMENT_SUCCESS_GET: "COMMENT_SUCCESS_GET",
    COMMENT_ERROR: "COMMENT_ERROR"
};

export const repoTypes = {
    REPO_LOAD: "REPO_LOAD",
    REPO_SUCESS: "REPO_SUCESS",
    REPO_ERROR: "REPO_ERROR"
};
