export const commentTypes = {
    COMMENT_LOAD: "COMMENT_LOAD",
    COMMENT_SUCESS_ADD: "COMMENT_SUCESS_ADD",
    COMMENT_SUCESS_GET: "COMMENT_SUCESS_GET",
    COMMENT_ERROR: "COMMENT_ERROR"
};

export const repoTypes = {
    REPO_LOAD: "REPO_LOAD",
    REPO_SUCESS: "REPO_SUCESS",
    REPO_ERROR: "REPO_ERROR"
};
